#!/bin/bash

if [ -z $IMAGE_REPO ]; then
  IMAGE_REPO=idstudios
fi 
IMAGE_NAME=drupal

echo "** Building Drupal **"
IMAGE_TAG=plain
docker build -t $IMAGE_REPO/$IMAGE_NAME:$IMAGE_TAG .
#docker push $IMAGE_REPO/$IMAGE_NAME:$IMAGE_TAG
