apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal7-drupal-files-volume
  labels:
    volume: drupal7-drupal-files-volume
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: "192.168.1.107"
    path: "/idstudios-files-drupal-test"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: drupal7-drupal-files-volume-claim
  namespace: web
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      volume: drupal7-drupal-files-volume
---
apiVersion: v1
kind: Service
metadata:
  name: drupal7-drupal-lb
  namespace: web
spec:
  ports:
  - port: 8000
    targetPort: 80
    protocol: TCP
  selector:
    app: drupal7-drupal
  type: LoadBalancer